<?php
//只支持一层配置覆盖
return [
    'ueditor_api'=>env('UEDITOR_API', '/wangpkg/ueditor'),
    'upapi' => env('UP_API', '/wangpkg/upload'),
    'upkey' => env('UP_KEY',''), //上传安全key
    'pagename' => 'wangpkgConfig1',
    'JWT_SECRET' => env('JWT_SECRET', 'XffANp_xxOeD2meV8龘HKBAR9xx3ef^FaLw&f3pE7UK7E2_9龘4zAT53Pb^C䟆ziM5VI@y95yyUR龘IPXCfGUiizONWEvoX_F3M7oDrLnnTs7T1'),
    'JWT_TTL' => env('JWT_TTL', 1296000),
    'JWT_MULTI_TERMINAL_LOGIN' => env('JWT_MULTI_TERMINAL_LOGIN', true),
    'ueditor_config'=>[
        'imageActionName' => 'uploadimage',
        'imageFieldName' => 'upfile',
        'imageMaxSize' => 2048000,
        'imageAllowFiles' =>
            array (
                0 => '.png',
                1 => '.jpg',
                2 => '.jpeg',
                3 => '.gif',
                4 => '.bmp',
            ),
        'imageCompressEnable' => true,
        'imageCompressBorder' => 1600,
        'imageInsertAlign' => 'none',
        'imageUrlPrefix' => '//imgs.1jiedan.com/',
        'imagePathFormat' => '/storage/upload/{yyyy}{mm}{dd}/{time}{rand:6}',
        'scrawlActionName' => 'uploadscrawl',
        'scrawlFieldName' => 'upfile',
        'scrawlPathFormat' => '/storage/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}',
        'scrawlMaxSize' => 2048000,
        'scrawlUrlPrefix' => '',
        'scrawlInsertAlign' => 'none',
        'snapscreenActionName' => 'uploadimage',
        'snapscreenPathFormat' => '/storage/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}',
        'snapscreenUrlPrefix' => '',
        'snapscreenInsertAlign' => 'none',
        'catcherLocalDomain' =>
            array (
                0 => '127.0.0.1',
                1 => 'localhost',
                2 => 'img.baidu.com',
            ),
        'catcherActionName' => 'catchimage',
        'catcherFieldName' => 'source',
        'catcherPathFormat' => '/storage/upload/image/{yyyy}{mm}{dd}/{time}{rand:6}',
        'catcherUrlPrefix' => '',
        'catcherMaxSize' => 2048000,
        'catcherAllowFiles' =>
            array (
                0 => '.png',
                1 => '.jpg',
                2 => '.jpeg',
                3 => '.gif',
                4 => '.bmp',
            ),
        'videoActionName' => 'uploadvideo',
        'videoFieldName' => 'upfile',
        'videoPathFormat' => '/storage/upload/video/{yyyy}{mm}{dd}/{time}{rand:6}',
        'videoUrlPrefix' => '',
        'videoMaxSize' => 102400000,
        'videoAllowFiles' =>
            array (
                0 => '.flv',
                1 => '.swf',
                2 => '.mkv',
                3 => '.avi',
                4 => '.rm',
                5 => '.rmvb',
                6 => '.mpeg',
                7 => '.mpg',
                8 => '.ogg',
                9 => '.ogv',
                10 => '.mov',
                11 => '.wmv',
                12 => '.mp4',
                13 => '.webm',
                14 => '.mp3',
                15 => '.wav',
                16 => '.mid',
            ),
        'fileActionName' => 'uploadfile',
        'fileFieldName' => 'upfile',
        'filePathFormat' => '/storage/upload/{yyyy}{mm}{dd}/{time}{rand:6}',
        'fileUrlPrefix' => '',
        'fileMaxSize' => 51200000,
        'fileAllowFiles' =>
            array (
                0 => '.png',
                1 => '.jpg',
                2 => '.jpeg',
                3 => '.gif',
                4 => '.bmp',
                5 => '.flv',
                6 => '.swf',
                7 => '.mkv',
                8 => '.avi',
                9 => '.rm',
                10 => '.rmvb',
                11 => '.mpeg',
                12 => '.mpg',
                13 => '.ogg',
                14 => '.ogv',
                15 => '.mov',
                16 => '.wmv',
                17 => '.mp4',
                18 => '.webm',
                19 => '.mp3',
                20 => '.wav',
                21 => '.mid',
                22 => '.rar',
                23 => '.zip',
                24 => '.tar',
                25 => '.gz',
                26 => '.7z',
                27 => '.bz2',
                28 => '.cab',
                29 => '.iso',
                30 => '.doc',
                31 => '.docx',
                32 => '.xls',
                33 => '.xlsx',
                34 => '.ppt',
                35 => '.pptx',
                36 => '.pdf',
                37 => '.txt',
                38 => '.md',
                39 => '.xml',
            ),
        'imageManagerActionName' => 'listimage',
        'imageManagerListPath' => '/storage/upload/',
        'imageManagerListSize' => 20,
        'imageManagerUrlPrefix' => '',
        'imageManagerInsertAlign' => 'none',
        'imageManagerAllowFiles' =>
            array (
                0 => '.png',
                1 => '.jpg',
                2 => '.jpeg',
                3 => '.gif',
                4 => '.bmp',
            ),
        'fileManagerActionName' => 'listfile',
        'fileManagerListPath' => '/storage/upload/',
        'fileManagerUrlPrefix' => '',
        'fileManagerListSize' => 20,
        'fileManagerAllowFiles' =>
            array (
                0 => '.png',
                1 => '.jpg',
                2 => '.jpeg',
                3 => '.gif',
                4 => '.bmp',
                5 => '.flv',
                6 => '.swf',
                7 => '.mkv',
                8 => '.avi',
                9 => '.rm',
                10 => '.rmvb',
                11 => '.mpeg',
                12 => '.mpg',
                13 => '.ogg',
                14 => '.ogv',
                15 => '.mov',
                16 => '.wmv',
                17 => '.mp4',
                18 => '.webm',
                19 => '.mp3',
                20 => '.wav',
                21 => '.mid',
                22 => '.rar',
                23 => '.zip',
                24 => '.tar',
                25 => '.gz',
                26 => '.7z',
                27 => '.bz2',
                28 => '.cab',
                29 => '.iso',
                30 => '.doc',
                31 => '.docx',
                32 => '.xls',
                33 => '.xlsx',
                34 => '.ppt',
                35 => '.pptx',
                36 => '.pdf',
                37 => '.txt',
                38 => '.md',
                39 => '.xml',
            ),
    ]
];
